In [1]:
import pandas as pd
import numpy as np

from sklearn.metrics.pairwise import cosine_similarity
from sklearn import preprocessing

In [15]:
df = pd.read_csv(r"CropProps.csv")



rainfallFeatures = ['RainfallLow', 'RainfallMed', 'RainfallHigh', 'Winter']
for f in rainfallFeatures:
    df[f] = df[f].fillna(False)

le = preprocessing.LabelEncoder()
le.fit(df[['Maturity', 'Winter']])


ValueError: y should be a 1d array, got an array of shape (66, 2) instead.

In [14]:
crops = df[['RainfallLow', 'RainfallMed', 'RainfallHigh', 'Winter']]

In [8]:
cosine_sim = cosine_similarity(crops)



In [10]:
print (cosine_sim)


[[1.         0.5        0.81649658 ... 0.81649658 0.81649658 0.5       ]
 [0.5        1.         0.81649658 ... 0.40824829 0.40824829 0.        ]
 [0.81649658 0.81649658 1.         ... 0.66666667 0.66666667 0.40824829]
 ...
 [0.81649658 0.40824829 0.66666667 ... 1.         1.         0.81649658]
 [0.81649658 0.40824829 0.66666667 ... 1.         1.         0.81649658]
 [0.5        0.         0.40824829 ... 0.81649658 0.81649658 1.        ]]
